### ISSUE TITLE
Don't upload .git directory to WorkShop

### ISSUE THREAD

**Issue by czp3009** [NtechMods/Vanilla-core-weapons#2]
.git directory is useless for mod running.

btw, plz use .wtignore to exclude files.

https://github.com/NtechMods/Vanilla-core-weapons/pull/1

**Comment by nukeguard** [comment]
ah yea, i mean to upload to workshop with SEWT which I ignore all files unnecessary to mod as I use git as backup to mod folder

**Comment by nukeguard** [comment]
unless git can have steam ignore files on upload

**Comment by czp3009** [comment]
in script 'Upload_to_Workshop_*.bat', '.git' directory not exclude.

this mod now has a size of 4.6MiB in workshop, if exclude '.git' directory, it's only few KiB.

Furthermore, you can use wtignore to ignore files. if u don't want to use wtignore, Please at least modify the script to ignore the 
'.git' folder.

**Comment by nukeguard** [comment]
I forgot bout this, adding to bat file to ignore, and I think I have .wtignore setup right now for SEWT

**Comment by czp3009** [comment]
thanks
